@startuml
interface Adaptee{
+{abstract} specificRequest()
}
interface Target{
+{abstract} request()
}
class ConcreteAdaptee{
+specificRequest()
}
class ConcreteTarget{
}
class Adapter{
-Adaptee adaptee
-Target target
+Adapter(Target target)
+Adapter(Adaptee adaptee)
+request()
+specificRequest()
}
note bottom:target.request(),\nadaptee.specificRequest();

Adapter .up.|> Adaptee
Adapter .up.|> Target
Adapter -up-> Adaptee
Adapter -up-> Target

ConcreteAdaptee .up.|> Adaptee
ConcreteTarget .up.|>Target



@enduml