" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.

set vb t_vb=
au GuiEnter * set t_vb=

set guifont=courier_new:h11
set nu
" 忽略大小写
set ic
set enc=UTF-8
set langmenu=zh_CN.UTF-8
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

set noundofile
set nobackup
set noswapfile
set tabstop=4
set shiftwidth=4
set textwidth=0
set wrapmargin=0

"不显示工具/菜单栏
set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=b
" 使用内置 tab 样式而不是 gui
set guioptions-=e

" 保存时路径补全
set wildmenu
set wildmode=list:full,full

vnoremap <C-C> "+y
vnoremap <C-X> "+x
noremap <C-Q> <C-V>
noremap <C-V> "+gp
cmap <C-V> <C-R>+

set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set encoding=utf-8
set termencoding=cp936
language messages zh_CN.UTF-8


" 启用 vim-devicons
let g:webdevicons_enable = 1

" 在 NERDTree 中显示图标
let g:WebDevIconsUnicodeDecorateFolderNodes = 1

" 设置图标默认不闪烁
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '

" 为 NERDTree 设置图标大小（可选）
let g:WebDevIconsNerdTreeGitMode = 1

" 显示文件类型图标
let g:WebDevIconsShowFileTypes = 1

" 在终端中也显示图标
let g:WebDevIconsShowOnTabline = 1


" 为 JSON 文件启用折叠功能
augroup json_tree_view
    autocmd!
    autocmd FileType json setlocal foldmethod=indent
    autocmd FileType json setlocal foldlevelstart=99
    autocmd FileType json setlocal expandtab
    autocmd FileType json setlocal shiftwidth=2
    autocmd FileType json setlocal softtabstop=2
augroup END

command! Jsonf :execute '%!python -m json.tool --no-ensure-ascii'

" set the runtime path to include Vundle and initialize
"set rtp+=D:/Applications/Scoop/apps/vim/bundle/Vundle.vim

"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"Plugin 'VundleVim/Vundle.vim'
"Plugin 'godlygeek/tabular' "必要插件，安装在vim-markdown前面
"Plugin 'plasticboy/vim-markdown'
"Plugin 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npm install mermaid@latest && cp node_modules/mermaid/dist/mermaid.min.js _static/mermaid.min.js' }
"Plugin 'elzr/vim-json'
"Plugin 'bling/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'
"Plugin 'preservim/nerdtree'
"Plugin 'fidian/hexmode'
"Plugin 'ryanoasis/vim-devicons'
"call vundle#end()

call plug#begin()

Plug 'godlygeek/tabular' "必要插件，安装在vim-markdown前面
Plug 'plasticboy/vim-markdown'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npm install mermaid@latest && cp node_modules/mermaid/dist/mermaid.min.js _static/mermaid.min.js' }
Plug 'elzr/vim-json'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'fidian/hexmode'
Plug 'ryanoasis/vim-devicons'

call plug#end()

nnoremap <A-1> :NERDTreeToggle<CR>

let g:vim_markdown_math = 1

if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

